@startuml
title Supuesto 6: Automatricula

actor Usuario #LightBlue

/'Casos de uso'/
"Seleccionar estudios" as (SE)
"Elegir año a cursar" as (EAC)
"Elegir materias" as (EM)
"Actualizar datos" as (AD)
"Seleccionar beca" as (SB)
"Seleccionar pago" as (SP)
"Descargar resguardo de matrícula" as (DRM)

/'Relaciones casos de usos'/
Usuario -right- (SE)
Usuario -up- (EAC)
Usuario -down- (EM)
Usuario -down- (AD)
Usuario -up- (SP)
Usuario -left- (SB)
Usuario -up- (DRM)

@enduml