@startuml automatricula
title Supuesto 6: Automatricula
left to right direction
actor Usuario #LightBlue

package Automatricula {
/'Casos de uso'/
"Seleccionar estudios" as (SE)
"Elegir año a cursar" as (EAC)
"Elegir materias" as (EM)
"Actualizar datos" as (AD)
"Seleccionar beca" as (SB)
"Seleccionar pago" as (SP)
"Descargar resguardo de matrícula" as (DRM)
}
/'Relaciones casos de usos'/


Usuario - (SE)
Usuario - (EAC)
Usuario - (EM)
Usuario - (AD)
Usuario - (SP)
Usuario - (SB)
Usuario - (DRM)


@enduml