@startuml compañiaHotelera
title Supuesto 3: Compañia Hotelera

actor Cliente #LightBlue
actor Comun #LightBlue
actor Comercial #LightBlue
actor Administrador #LightBlue

/'Herencias'/
Comun -up-|> Cliente
Administrador -up-|> Comun
Comercial -up-|> Comun

/'Casos de uso'/
"Consultar disponibilidades" as (CD)
"Mostrar calendario" as (MC)
"Visualizar ofertas" as (VO)
"Buscar elementos" as (BE)
"Consultar reservas" as (CR)
"Recalcular precios" as (RP)
"Bloquear reserva temporalmente" as (BRT)
"Realizar ofertas" as (RO)
"Gestionar peticiones nuevas" as (GPN)
"Gestionar nuevas reservas" as (GNR)
"Mostrar calendario" as (MC)
"Consultar" as (C)  

usecase ROV as "Realizar ofertas vista comercial
--
extension points
Bloquear reserva temporalmente"

/'Relaciones casos de uso'/
Cliente -left- (VO)
Cliente -right- (CD)
(CD) .-down-> (MC) : <<include>>
Comun - (CR)
Administrador -down- (RO)
Administrador -down- (GPN)
Comercial -down- (GNR)
Comercial -down- (ROV)
(ROV) .-up-> (RP) : <<include>>
(BRT) .> (ROV) : <<extend>>
(ROV) -|> (RO)
(CD) -|> (C)
(CR) -|> (C)
(C) .-> (BE) : <<include>>
@enduml