@startuml compañiaHotelera
title Supuesto 3: Compañia Hotelera

actor Comun #LightBlue
actor Comun2 #LightBlue
actor Comercial #LightBlue
actor Administrador #LightBlue

/'Herencias'/
Comun2 -up-|> Comun
Administrador -up-|> Comun2
Comercial -up-|> Comun2

/'Casos de uso'/
"Consultar disponibilidades" as (CD)
"Mostrar calendario" as (MC)
"Visualizar ofertas" as (VO)
"Buscar elementos" as (BE)
"Consultar reservas" as (CR)
"Recalcular precios" as (RP)
"Bloquear reserva temporalmente" as (BRT)
"Realizar ofertas" as (RO)
"Gestionar peticiones nuevas" as (GPN)
"Gestionar nuevas reservas" as (GNR)

usecase ROV as "Realizar ofertas vista comercial
--
extension points
Bloquear reserva temporalmente"

/'Relaciones casos de uso'/
Comun -right- (VO)
Comun -left- (CD)
(CD) .-down-> (BE) : <<include>>
(VO) .-down-> (MC) : <<include>>
Comun2 - (CR)
(CR) .> (RP) : <<include>>
Administrador -down- (RO)
Administrador -down- (GPN)
Comercial -down- (GNR)
Comercial -down- (ROV)
(ROV) .> (RP) : <<include>>
(BRT) .> (ROV) : <<extend>>
(ROV) -|> (RO)
@enduml