@startuml gestionDeIncidencias
title Supuesto 5: Gestión de Incidencias

actor Administrador #LightBlue
actor Tecnico #LightBlue
actor Operador #LightBlue
actor UsuarioInvitado #LightBlue
actor GestorDeCorreo #LightBlue
actor Comun #LightBlue
actor Comun2 #LightBlue 

/'DEFINICIONES DE CASOS DE USO'/
"Gestionar categorias de incidencias" as (GCI)
"Ordenar incidencias vista Administrador" as (OIVA)
"Añadir comentario" as (AC)
"Realizar informe sobre incidencias" as (RISI)
"Atender llamada vista Tecnico" as (ALVT)
"Comprobar datos" as (CD)
"Ordenar incidencias" as (OI)
"Marcar incidencias duplicadas" as (MID)
"Atender llamada vista Operador" as (ALVO)
"Introducir nuevos datos" as (IND)
"Atender llamada" as (AL)
"Acceder listado historico de notificaciones" as (ALHN)
"Ver notificaciones" as (VN)
"Consultar incidencias" as (CI)
"Informar incidencias" as (II)
"Dar de alta localizacion" as (DAL)
"Incorporar explicacion" as (IE)
"Subir foto" as (SF)
"Registrar" as (R)
"Enviar correo" as (EC)
"Editar datos" as (ED)

usecase DAI as "Dar alta incidencias
--
extension points
Enviar correo"

usecase CIVT as "Consultar incidencias vista trabajadores
--
extension points
Editar datos"

/'HERENCIAS ENTRE ACTORES'/
Administrador -|> Comun2
Operador -up-|> Comun
Operador -|> Comun2
Tecnico -|> Comun
Tecnico -|> Comun2

/'RELACIONES DE LOS CASOS DE USO'/
Administrador -up- (GCI)
Administrador -down- (OIVA)
(OIVA) .down.> (AC) : <<include>>
(OIVA) -|> (OI)
Tecnico -left- (RISI)
Tecnico -down- (ALVT)
(ALVT) .down.> (CD) : <<include>>
(ALVT) -down-|> (AL)
Operador -left- (MID)
Operador - (ALVO)
Operador - (OI)
(ALVO) .down.> (IND) : <<include>>
(ALVO) -|> (AL)
UsuarioInvitado -down- (ALHN)
UsuarioInvitado -right- (CI)
UsuarioInvitado -down- (R)
UsuarioInvitado -down- (II)
UsuarioInvitado - (VN)
(II) .down.> (DAL) : <<include>>
(II) .down.> (IE) : <<include>>
(II) .down.> (SF) : <<include>>
Comun -down- (DAI)
(EC) .down.> (DAI) : <<extend>>
GestorDeCorreo - (DAI)
Comun2 -down- (CIVT)
(ED) .right.> (CIVT) : <<extend>>
(CIVT) -down-|> (CI)

@enduml