@startuml horarios
title Supuesto 1: Horarios
:PDI:
:PAS:
:Estudiante:
PDI - (Proponer cambio de horario)
PDI - (Dar de alta estudiante vista PDI)
PAS -- (Dar de alta estudiante) 
(Dar de alta estudiante) .> (Verificar datos estudiantes) : include
PAS - (Modificar horario) 
Estudiante - ("Consultar horarios")
@enduml