@startuml horarios
title Supuesto 1: Horarios
:PDI:
:PAS:
:Estudiante:
Estudiante - (Consultar horarios)
PDI -- (Proponer cambio de horario)
PDI -- (Dar de alta estudiante vista PDI)
(Dar de alta estudiante vista PDI) --|> (Dar de alta estudiante)  
(Buscar listas de clase) .> (Dar de alta estudiante vista PDI) : extend
PAS -- (Dar de alta estudiante) 
(Dar de alta estudiante) .> (Verificar datos estudiantes) : include
PAS -- (Modificar horario) 
PDI --|> Estudiante
PAS --|> Estudiante
@enduml