@startuml horarios
title Supuesto 1: Horarios
:PDI:
:PAS:
:Estudiante:
PDI -> ("Proponer cambio de horario" )
"Proponer cambio de horario" 
PDI -> (UC2)
"Dar de alta estudiante (vista PDI)" 
"Dar de alta estudiante" 
PAS -> (UC4)
"Modificar horario" 
@enduml