@startuml SIIT
title Sistema de información

actor Usuario #LightBlue
actor Administrador #LightBlue

/'Casos de uso'/
"Obtener ayuda en línea" as (OAL)
"Realizar consulta" as (RC)
"Introducir potenciador" as (IP)
"Introducir fecha y hora" as (IFH)
"Usar mapa" as (UM)

"Ver horario y líneas" as (VHLU)
"Ver horario y líneas (vista Administrador)" as (VHLA)
"Modificar datos" as (MD)

"Introducir datos" as (IMD)

usecase VIC as "Ver información cartográfica"

usecase SOD as "Seleccionar origen y destino
--
extension points
Usar mapa"

usecase VR as "Ver resultado"

/'Relaciones casos de uso'/
Usuario -- (OAL)
Usuario -- (RC)
Usuario -- (VIC)
(RC) .-> (IP) : <<include>>
(RC) .-> (IFH) : <<include>>
(RC) .-> (SOD) : <<include>>
(UM) .-> (SOD) : <<extend>>
(RC) .-> (VR) : <<include>>
Usuario -up- (VHLU)

Administrador -- (VHLA)
(VHLA) -|> (VHLU)
Administrador -- (MD)
Administrador -- (IMD)





