@startuml sistemaDeCompras
title Supuesto 2: Sistema de Compras

actor Comun #LightBlue
actor Comprador #LightBlue
actor Vendedor #LightBlue
actor Proveedor #LightBlue
actor Administrador #LightBlue

/'Casos de uso'/
"Consultar ofertas" as (CO)
"Consultar precios" as (CP)

usecase RV as "Realizar venta
--
extension points
Consultar historico de ventas"

"Consultar historico de ventas" as (CHV)
"Acordar precio" as (AP)
"Agregar productos" as (AProd)
"Consultar productos" as (CProd)
"Finalizar compra" as (FC)
"Verificar disponibilidad" as (VD)
"Marcar productos como bloqueados" as (MPB)
"Avisar fin de oferta" as (AFO)
"Eliminar oferta" as (EO)
"Avisar" as (A)

usecase ANP as "Avisar nuevos productos
--
extension points
Incorporar oferta"

"Incorporar oferta" as (IO)
"Enviar notificacion" as (EN)
"Eliminar producto" as (EP)
"Buscar productos" as (BP)

/'Herencias actores'/
Administrador -up-|> Comun
Comprador -up-|> Comun
Vendedor -up-|> Comun
Proveedor -up-|> Comun

/'Relaciones casos de uso'/
Comun -up- (CO)
Comun -left- (CP)
Comprador -down- (RV)
Vendedor -down- (RV)
Comprador -left- (AProd)
Comprador - (CProd)
Comprador -down- (FC)
Proveedor -left- (AFO)
Proveedor - (ANP)
Administrador - (EP)
(RV) .-left-> (AP) : <<include>>
(CHV) .-left-> (RV) : <<extend>>
(AProd) .-down-> (MPB) : <<include>>
(CProd) .-down-> (VD) : <<include>>
(AFO) .-down-> (EO) : <<include>>
(A) .-down-> (EN) : <<include>>
(IO) .-down-> (ANP) : <<extend>>
(AFO) -down-|> (A)
(ANP) -|> (A)
(CP) .-> (BP) : <<include>>
(CProd) -|> (BP)

@enduml